// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddVancanciesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addVancancies() {
    driver.Navigate().GoToUrl("http://localhost/orangehrm-5.4/orangehrm-5.4/web/index.php/dashboard/index");
    driver.Manage().Window.Size = new System.Drawing.Size(1051, 798);
    driver.FindElement(By.LinkText("Recruitment")).Click();
    {
      var element = driver.FindElement(By.LinkText("Recruitment"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".oxd-topbar-body-nav-tab:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".oxd-button--secondary:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".oxd-input--focus")).Click();
    driver.FindElement(By.CssSelector(".oxd-input--focus")).SendKeys("Co");
    driver.FindElement(By.CssSelector(".oxd-input--focus")).SendKeys("Tester");
    driver.FindElement(By.CssSelector(".bi-caret-up-fill")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".oxd-textarea"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
  }
}
