// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LogoutTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void logout() {
    driver.Navigate().GoToUrl("http://localhost/orangehrm-5.4/orangehrm-5.4/web/index.php/auth/login");
    driver.Manage().Window.Size = new System.Drawing.Size(1102, 804);
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys("tuongma");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("Tuong*123");
    driver.FindElement(By.Name("password")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".oxd-userdropdown-tab")).Click();
    driver.FindElement(By.LinkText("Logout")).Click();
    var elements = driver.FindElements(By.CssSelector(".oxd-button"));
    Assert.True(elements.Count > 0);
  }
}
